// Generated by LiveScript 1.5.0
$(function(){
  var clientId, params, headers, listAlbums, uploadUrl, q, handleUrl, handlePaste;
  clientId = $('#client-id').val();
  $('#client-id').on('change', function(){
    clientId = this.value;
    return $('#login').attr('href', "https://api.imgur.com/oauth2/authorize?client_id=" + clientId + "&response_type=token");
  }).trigger('change');
  params = function(){
    var p, hash, data, m, ref$, key, value;
    p = /([^&=]+)=([^&]*)/g;
    hash = location.hash.slice(1);
    data = {};
    while (m = p.exec(hash)) {
      ref$ = m.map(decodeURIComponent), key = ref$[1], value = ref$[2];
      data[key] = value;
    }
    return data;
  }();
  headers = {
    Authorization: "Bearer " + params.access_token
  };
  listAlbums = function(){
    var url, this$ = this;
    url = "https://api.imgur.com/3/account/" + params.account_username + "/albums";
    return fetch(url, {
      headers: headers
    }).then(function(it){
      return it.json();
    });
  };
  uploadUrl = function(it){
    var data, ref$, body, key, value, this$ = this;
    data = {
      image: it,
      album: $('#album').val(),
      type: 'URL',
      name: (ref$ = /\/([^/]+)$/.exec(it)) != null ? ref$[1] : void 8
    };
    body = new FormData;
    for (key in data) {
      value = data[key];
      body.append(key, value);
    }
    return fetch('https://api.imgur.com/3/image', {
      method: 'POST',
      body: body,
      headers: headers
    }).then(function(it){
      return it.json();
    });
  };
  q = queue();
  handleUrl = function(url){
    var status;
    status = $('<div>');
    $('#status').append(status);
    status.text("waiting: " + url);
    return q.add(function(){
      status.text("uploading: " + url);
      return uploadUrl(url);
    }).then(function(){
      return status.text("done: " + url);
    });
  };
  handlePaste = function(event){
    event.preventDefault();
    return event.clipboardData.getData('text').split('\n').forEach(handleUrl);
  };
  if (params.account_username) {
    listAlbums().then(function(arg$){
      var albums;
      albums = arg$.data;
      return $('#album').empty().prepend(albums.map(function(arg$){
        var title, id;
        title = arg$.title, id = arg$.id;
        return $('<option>').text(title).attr('value', id);
      }));
    });
  }
  return document.querySelector('#urls').addEventListener('paste', handlePaste);
});